name: pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: instalar python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
    
      - name: instalar uv
        run: pipx install uv

      - name: instalar dependencias
        run: uv sync